version: '2.1'
services:
  web:
    build: .
    command: python manager.py run
    ports:
      - 5000:5000
    env_file:
      - .env
    restart: always
    depends_on:
     - db
  db:
    image: postgres:11
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - app/config/docker.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
     - db 
volumes:
  postgres_data:

